language: python
python:
    - "3.4"
sudo: false

matrix:
  fast_finish: true

install:
  - pip install flake8
  - pip install pyfrc
  - pip install pytest
  - pip install mock

script:
    - flake8 kiwidrive
    - flake8 tiredrive
    - python tiredrive/robot.py test tests.py
