language: python
python:
    - "3.4"
sudo: false

matrix:
  fast_finish: true

env:
    - TESTS=flake8-kiwidrive
    - TESTS=flake8-tiredrive
    - TESTS=tiredrive-unittests
    - TESTS=kiwidrive-unittests

install:
  - pip install flake8
  - pip install pyfrc
  - pip install pytest
  - pip install mock

script:
    - ./travis.sh $TESTS
